feat: Redux leaderboard & battletv page
delta/codecharacter-web-2022 pull request #23
Opened 2022-02-10 07:15 UTC by jaiakash

- [ ] Fetch from server to display on leaderboard page
- [ ] Fetch from server to display on battletv page
- [ ] Implement redux for battletv page

2022-02-11 20:47 UTC, nishihere19 approved these changes

2022-02-11 20:47 UTC, nishihere19 commented
Avatars are broken, apart from that everything looks fine to me.

2022-02-12 04:30 UTC, jaiakash commented
- **Leaderboard** Data is fetched each time component is loaded.
- **BattleTV** Data is fetched only once when the components load for the first time.

> Avatars are broken, apart from that everything looks fine to me.

It would be integrated later when assets are decided.

2022-02-12 15:35 UTC, PriyanshuDangi requested changes
![image](https://user-images.githubusercontent.com/51911161/153717655-41ecc7cb-6f3f-44be-8079-1e3b85c921da.png)

boxes are not same size

2022-02-12 16:15 UTC, PriyanshuDangi requested changes

2022-02-12 16:15 UTC, PriyanshuDangi commented on src/components/Leaderboard/Leaderboard.tsx
> +    console.log(event);
remove

2022-02-12 20:16 UTC, jaiakash commented on src/components/BattleTV/BattleTV.tsx
> +  const itemsPerPage = 4;
For testing purpose (pagination, just 4 so that it has multiple pages), i hardcoded it.

2022-02-12 21:38 UTC, jaiakash commented
> Add loader till it loads the leaderboard also add a refresh button somewhere on leaderboard which will fetch the updated leaderboard from the backend

Done :+1:

2022-02-13 07:28 UTC, jaiakash commented on src/components/BattleTV/BattleTV.tsx
> +  if (battletv.length === 0) {
Added new field ```hasbeenFetched```.

2022-02-13 11:50 UTC, PriyanshuDangi approved these changes

2022-02-13 11:51 UTC, merged