feat: Add Navbar, Sidebar, Toast
delta/codecharacter-web-2022 pull request #7
Opened 2022-01-26 03:40 UTC by vigneshd332

### Changes
<ul>
<li> Add Navbar, sidebar and toast notifs</li>
</ul>

2022-01-28 13:29 UTC, PriyanshuDangi commented on src/components/NavBar/NavBar.tsx
> +import './NavBar.css';
use css modules

2022-01-28 13:29 UTC, PriyanshuDangi commented on src/components/SideBar/SideBar.tsx
> +import './SideBar.css';
everywhere

2022-01-29 08:31 UTC, vigneshd332 commented on src/components/NavBar/NavBar.tsx
> +import './NavBar.css';
done na, updated

2022-01-31 10:48 UTC, PriyanshuDangi commented
![image](https://user-images.githubusercontent.com/51911161/151780561-0ae0b3e9-0b50-41e4-a7b2-91c71d43b86f.png)

2022-01-31 11:13 UTC, CaptainIRS requested changes
Add tooltips for the sidebar icons. You can use the [title](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) attribute to keep things simple.

2022-02-01 15:40 UTC, CaptainIRS approved these changes
LGTM

2022-02-01 15:41 UTC, merged